export enum Events {
	CLICK = "click",
	KEYDOWN = "keydown",
	KEYUP = "keyup",
	KEYPRESS = "keypress",
	MOUSEENTER = "mouseenter",
	MOUSELEAVE = "mouseleave",
	FOCUS = "focus",
	BLUR = "blur",
	CHANGE = "change",
	SUBMIT = "submit",
	SCROLL = "scroll",
	RESIZE = "resize",
	LOAD = "load",
	UNLOAD = "unload",
	ERROR = "error",
	ENTER = "Enter",
}
